FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production

FROM gcr.io/distroless/nodejs24-debian13
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY server.js ./
COPY package.json ./
COPY --from=build --chown=65532:65532 /app /app
COPY logs ./
USER 65532
EXPOSE 3000
CMD ["server.js", "development"]

