sonar.projectKey=nodeapp
sonar.projectName=nodeapp
sonar.sources=.
sonar.host.url=http://localhost:9003
sonar.login=squ_5efcf7e51e96062c455957df8c2ad46af460ff33

#sonar.projectKey=nodeapp
#sonar.projectName=nodeapp
#sonar.sources=.
#sonar.host.url=http://localhost:9003
#sonar.login=admin
#sonar.password=admin
