name: CI pipeline

on: 
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  docker_push:
    runs-on: [self-hosted, wsl1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login, Build, Push image to Dockerhub
        uses: karthipv-07/Revamp-Batch-03/.github/actions/docker-build-push@main
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
