name: Basic Node pipeline with env

on:
  workflow_dispatch: 
  # push:
  #   branches: ["main"]

jobs:
  node-build:
    runs-on: [self-hosted, wsl1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create env file
        run: |
          echo "PORT=3000" >> .env.development
          echo "APP=NODE_DEV_APP" >> .env.development
          echo "PORT=8080" >> .env.production
          echo "APP=NODE_PROD_APP" >> .env.production
          
      - name: Run application
        run: node server.js
