name: NodeApp CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  sonarqube-check:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

     # - name: SonarQube Scan
     #   uses: SonarSource/sonarqube-scan-action@v5
     #   env:
     #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     #   with:
     #     args: >
     #       -Dsonar.projectKey=nodeapp
     #       -Dsonar.host.url=http://localhost:9003

      - name: SonarQube Placeholder
        run: echo "SonarQube step configured"

  docker-build-push:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Composite Action
        uses: ./.github/actions/docker-build-push
        with:
          image_name: karthickrajadevops/nodeapp
          image_tag: latest
